# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wardbuddy',
                'doc_host': 'https://Dyadd.github.io',
                'git_url': 'https://github.com/Dyadd/wardbuddy',
                'lib_path': 'wardbuddy'},
  'syms': {'wardbuddy.core': {'wardbuddy.core.foo': ('core.html#foo', 'wardbuddy/core.py')}}}
